=head1 Frequent mod_perl problems

=head1 Coverage

Some problems come up very often on the mailing list.  If there is
some important problem that is being reported frequently on the list
which is not included below, even if it is found elsewhere in the Guide,
please L<tell me|help/Contacting_me>.


=head1 my() scoped variable in nested subroutines

See the section "L<my() Scoped Variable in Nested 
Subroutines|perl/my_Scoped_Variable_in_Nested_S>".



=head1 Segfaults caused by PerlFreshRestart

See the section L<Evil things might happen when using
PerlFreshRestart|troubleshooting/Evil_things_might_happen_when_us>


=cut

